version: '3.8'

services:
  rhul-00-01:
    build:
      context: ./challenges/00-introduction/01-outsourced-computation
    container_name: rhul_00_01
    restart: unless-stopped
    tty: true
    ports:
      - "${R00_01_PORT}:${R00_01_CHAL_PORT}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    networks:
      - internal

  rhul-01-00:
    build:
      context: ./challenges/01-defining-mpc/00-semihonest-security
    container_name: rhul_01_00
    restart: unless-stopped
    tty: true
    ports:
      - "${R01_00_PORT}:${R01_00_CHAL_PORT}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    networks:
      - internal

  rhul-01-01:
    build:
      context: ./challenges/01-defining-mpc/01-malicious-security
    container_name: rhul_01_01
    restart: unless-stopped
    tty: true
    ports:
      - "${R01_01_PORT}:${R01_01_CHAL_PORT}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    networks:
      - internal

  rhul-01-02:
    build:
      context: ./challenges/01-defining-mpc/02-ot
    container_name: rhul_01_02
    restart: unless-stopped
    tty: true
    ports:
      - "${R01_02_PORT}:${R01_02_CHAL_PORT}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    networks:
      - internal

  rhul-01-03:
    build:
      context: ./challenges/01-defining-mpc/03-zkp
    container_name: rhul_01_03
    restart: unless-stopped
    tty: true
    ports:
      - "${R01_03_PORT}:${R01_03_CHAL_PORT}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    networks:
      - internal

  rhul-02-00:
    build:
      context: ./challenges/02-foundamentals-mpc-protocols/00-lut
    container_name: rhul_02_00
    restart: unless-stopped
    tty: true
    ports:
      - "${R02_00_PORT}:${R02_00_CHAL_PORT}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    networks:
      - internal

  rhul-02-03:
    build:
      context: ./challenges/02-foundamentals-mpc-protocols/03-two-party-gmw
    container_name: rhul_02_03
    restart: unless-stopped
    tty: true
    ports:
      - "${R02_03_PORT}:${R02_03_CHAL_PORT}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    networks:
      - internal

  rhul-02-04:
    build:
      context: ./challenges/02-foundamentals-mpc-protocols/04-faulty-gmw
    container_name: rhul_02_04
    restart: unless-stopped
    tty: true
    ports:
      - "${R02_04_PORT}:${R02_04_CHAL_PORT}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    networks:
      - internal

  rhul-02-05:
    build:
      context: ./challenges/02-foundamentals-mpc-protocols/05-bgw
    container_name: rhul_02_05
    restart: unless-stopped
    tty: true
    ports:
      - "${R02_05_PORT}:${R02_05_CHAL_PORT}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    networks:
      - internal

  rhul-02-06:
    build:
      context: ./challenges/02-foundamentals-mpc-protocols/06-beaver-triples
    container_name: rhul_02_06
    restart: unless-stopped
    tty: true
    ports:
      - "${R02_06_PORT}:${R02_06_CHAL_PORT}"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    networks:
      - internal

networks:
  internal:
    driver: bridge