version: '3.8'

services:
  rhul-00-00:
    build:
      context: ./challenges/00-introduction/00-outsourced-computation
    container_name: rhul_00_00
    restart: unless-stopped
    tty: true
    ports:
      - "1337:1337"
    read_only: true

  rhul-01-00:
    build:
      context: ./challenges/01-defining-mpc/00-semihonest-security
    container_name: rhul_01_00
    restart: unless-stopped
    tty: true
    ports:
      - "1338:1338"
    read_only: true

  rhul-01-01:
    build:
      context: ./challenges/01-defining-mpc/01-malicious-security
    container_name: rhul_01_01
    restart: unless-stopped
    tty: true
    ports:
      - "1339:1339"
    read_only: true

  rhul-01-02:
    build:
      context: ./challenges/01-defining-mpc/02-ot
    container_name: rhul_01_02
    restart: unless-stopped
    tty: true
    ports:
      - "1340:1340"
    read_only: true

  rhul-01-03:
    build:
      context: ./challenges/01-defining-mpc/03-zkp
    container_name: rhul_01_03
    restart: unless-stopped
    tty: true
    ports:
      - "1341:1341"
    read_only: true

  rhul-02-00:
    build:
      context: ./challenges/02-foundamentals-mpc-protocols/00-lut
    container_name: rhul_02_00
    restart: unless-stopped
    tty: true
    ports:
      - "1342:1342"
    read_only: true

  rhul-02-01:
    build:
      context: ./challenges/02-foundamentals-mpc-protocols/01-intro-gc
    container_name: rhul_02_01
    restart: unless-stopped
    tty: true
    read_only: true

  rhul-02-02:
    build:
      context: ./challenges/02-foundamentals-mpc-protocols/02-deep-gc
    container_name: rhul_02_01
    restart: unless-stopped
    tty: true
    read_only: true

